// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: baseProject/test/test.proto

package test

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Сообщение
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_baseProject_test_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baseProject_test_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_baseProject_test_test_proto_rawDescGZIP(), []int{0}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_baseProject_test_test_proto protoreflect.FileDescriptor

const file_baseProject_test_test_proto_rawDesc = "" +
	"\n" +
	"\x1bbaseProject/test/test.proto\x12\x06parser\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2U\n" +
	"\vTestService\x12F\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x14.parser.PingResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/testB.Z,github.com/AdilBaidual/baseProject/test;testb\x06proto3"

var (
	file_baseProject_test_test_proto_rawDescOnce sync.Once
	file_baseProject_test_test_proto_rawDescData []byte
)

func file_baseProject_test_test_proto_rawDescGZIP() []byte {
	file_baseProject_test_test_proto_rawDescOnce.Do(func() {
		file_baseProject_test_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baseProject_test_test_proto_rawDesc), len(file_baseProject_test_test_proto_rawDesc)))
	})
	return file_baseProject_test_test_proto_rawDescData
}

var file_baseProject_test_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_baseProject_test_test_proto_goTypes = []any{
	(*PingResponse)(nil),  // 0: parser.PingResponse
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_baseProject_test_test_proto_depIdxs = []int32{
	1, // 0: parser.TestService.Ping:input_type -> google.protobuf.Empty
	0, // 1: parser.TestService.Ping:output_type -> parser.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_baseProject_test_test_proto_init() }
func file_baseProject_test_test_proto_init() {
	if File_baseProject_test_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baseProject_test_test_proto_rawDesc), len(file_baseProject_test_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baseProject_test_test_proto_goTypes,
		DependencyIndexes: file_baseProject_test_test_proto_depIdxs,
		MessageInfos:      file_baseProject_test_test_proto_msgTypes,
	}.Build()
	File_baseProject_test_test_proto = out.File
	file_baseProject_test_test_proto_goTypes = nil
	file_baseProject_test_test_proto_depIdxs = nil
}
