// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: api/test/tmp.proto

package test

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tmp_Tmp_FullMethodName = "/parser.Tmp/Tmp"
)

// TmpClient is the client API for Tmp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TmpClient interface {
	Tmp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TmpResp, error)
}

type tmpClient struct {
	cc grpc.ClientConnInterface
}

func NewTmpClient(cc grpc.ClientConnInterface) TmpClient {
	return &tmpClient{cc}
}

func (c *tmpClient) Tmp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TmpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TmpResp)
	err := c.cc.Invoke(ctx, Tmp_Tmp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TmpServer is the server API for Tmp service.
// All implementations must embed UnimplementedTmpServer
// for forward compatibility.
type TmpServer interface {
	Tmp(context.Context, *emptypb.Empty) (*TmpResp, error)
	mustEmbedUnimplementedTmpServer()
}

// UnimplementedTmpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTmpServer struct{}

func (UnimplementedTmpServer) Tmp(context.Context, *emptypb.Empty) (*TmpResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tmp not implemented")
}
func (UnimplementedTmpServer) mustEmbedUnimplementedTmpServer() {}
func (UnimplementedTmpServer) testEmbeddedByValue()             {}

// UnsafeTmpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TmpServer will
// result in compilation errors.
type UnsafeTmpServer interface {
	mustEmbedUnimplementedTmpServer()
}

func RegisterTmpServer(s grpc.ServiceRegistrar, srv TmpServer) {
	// If the following call pancis, it indicates UnimplementedTmpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tmp_ServiceDesc, srv)
}

func _Tmp_Tmp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TmpServer).Tmp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tmp_Tmp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TmpServer).Tmp(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Tmp_ServiceDesc is the grpc.ServiceDesc for Tmp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tmp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parser.Tmp",
	HandlerType: (*TmpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tmp",
			Handler:    _Tmp_Tmp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/test/tmp.proto",
}
